name: Push and build

on: [push]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Setup Node
          uses: actions/setup-node@v3
          with:
            node-version: 20
        - name: Install dependency
          run: | 
            npm init -y
            npm install 
        - name: Build project
          run: npm run build
